version: '2'
services:
  web:
    image: rrcfesc/pythonodoodocker:11.0
    ports:
      - "8069:8069"
    volumes:
      - ~/.ssh:/home/odoo/.ssh
      - ./odoo-repo:/home/odoo/odoo-repo
      - ./proyecto:/home/odoo/mymodules
      - ./config:/home/odoo/config
      - ./enterprise:/home/odoo/enterprise
      - ./mexico:/home/odoo/mexico
      - ./addons-vauxoo:/home/odoo/addons-vauxoo
      - ./server-tools:/home/odoo/server-tools
    container_name: odooskeleton-odoo
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10
    container_name: "odooskeleton_db"
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "odoo"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: odooskeleton
